# Generated by Django 3.1.2 on 2020-10-24 07:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.BooleanField(blank=True, default=False, verbose_name='Done?'),
        ),
    ]
